#!/bin/bash
APPDIR="${HOME}/.hueshell"

if ! [ -d ${APPDIR} ]; then
    mkdir -p ${APPDIR} || \
        ( echo "Could not initialize ${APPDIR}" && \
          echo "Please check that you have permission to create that directory" && \
          exit 1 )
fi

if [ -f ${APPDIR}/config ]; then
    . ${APPDIR}/config
fi
